#   Version 9.4.7

##############################################################
# default values for fields                                  #
##############################################################
